### PR TITLE
Update FontAwesome 4.3.0

### PR DESCRIPTION
**Pull request by yamasy1549**
Pulled fonts & scss from the current version(4.3.0) of FontAwesome

We'll be able to use `fa-pulse`:sparkles:

### CODE REVIEW

**Comment by osabate** [comment]
Can we close and merge this PR? Any ETA? Thanks!

**Comment by cristianferrarig** [comment]
@yamasy1549 thanks for the PR!
@osabate thanks for the reminder!

And sorry for the delay :(
Greetings!

**Comment by osabate** [comment]
Works! :+1:

**Comment by yamasy1549** [comment]
@osabate @cristianferrarig Thank you very much!! :oden:

**Pull request merged**
